# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ioannis Panagiotopoulos
# Description of the Site
description: Data Scientist | Physicist | Msc in Energy
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: gi.panagiotopoulos@gmail.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: giannispanagiotopoulos
github_username:  giannpan
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Ioannis Panagiotopoulos
# URL for the Image of the Author
author-image: https://media.licdn.com/dms/image/D4D03AQFeeOkbLjYScw/profile-displayphoto-shrink_800_800/0/1684738007879?e=1707955200&v=beta&t=Mop4g65XTU0mflOrEbgqPGy3-ON0LruY2XVvh5-y8wQ
# 60 Words About the Author
author-about: I have an academic background on Physics, Renewable energy sources and recently in Data Science. 
From 2015 till today I am running my own company in the field of LED lighting in Athens, Greece, but since I am a person that keeps looking for new adventures, during the last years I am focused on developing my Data Science skills.
The most important skill that I have obtained through my occupation in different business sectors, is to be a problem solver and to be passionate for optimizing processes.
My plans for the future is to improve my technical skills and go deeper in the Data Science world and more specifically in Machine Learning, Natural Language Processing (NLP), Artificial Intelligence and Neural Networks.
In my free time I try to keep up with the Technology changes and be informed about Finance and Business. I also like travelling and reading.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://giannpan.github.io/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
